"""Remove timeslot end time

Revision ID: 4e279b903637
Revises: f1451bcee9d9
Create Date: 2021-12-12 10:53:10.198395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e279b903637'
down_revision = 'f1451bcee9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeslot', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('end_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
