"""Initial migration

Revision ID: 9906a500ca0b
Revises: 
Create Date: 2021-12-11 11:29:32.554234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9906a500ca0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ack_at', sa.DateTime(), nullable=True),
    sa.Column('timeslot_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('timeslot')
    # ### end Alembic commands ###
