"""Add age ans vaccination to booking

Revision ID: b70da3d1ff07
Revises: 6e509ed3857b
Create Date: 2021-12-12 13:52:17.378566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70da3d1ff07'
down_revision = '6e509ed3857b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('age', sa.String(length=10), nullable=True))
    op.add_column('booking', sa.Column('vaccination', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'vaccination')
    op.drop_column('booking', 'age')
    # ### end Alembic commands ###
