"""Add timeslot capacity

Revision ID: d17530cd294c
Revises: 9906a500ca0b
Create Date: 2021-12-11 13:10:23.944414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17530cd294c'
down_revision = '9906a500ca0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeslot', 'capacity')
    # ### end Alembic commands ###
